Repository Domi-do/Domido, pull requests merged in 2025-06, with the labels that each got.

#45 Feat: 커서 도미노가 바닥 또는 다른 도미노 위에 정확히 올라가도록 위치 보정
  src/components/CursorFollowerObject/CursorFollowerObject.jsx
  src/components/Ground/Ground.jsx
  src/pages/DominoScene.jsx
Labels: enhancement, FE

#61 Refactor: 컴포넌트 폴더 구조 역할 기반으로 리팩토링 및 Barrel Export 적용
  public/objects/lightbulb.glb
  public/objects/slide.glb
  public/objects/spiral_stairs.glb
  src/components/Common/GlobalAudio.jsx
  src/components/Common/GlobalPortal.jsx
  src/components/Common/Loading.jsx
  src/components/Common/ModalOverlay.jsx
  src/components/DominoCanvas/CameraControls/CameraControls.jsx
  src/components/DominoCanvas/CursorFollowerObject/CursorFollowerObject.jsx
  src/components/DominoCanvas/DominoCanvas.jsx
  src/components/DominoCanvas/Ground/Ground.jsx
  src/components/DominoCanvas/ObjectRenderer/ObjectRenderer.jsx
  src/components/DominoCanvas/index.js
  src/components/DominoHUD/DominoClearConfirmModal/DominoClearConfirmModal.jsx
  src/components/DominoHUD/DominoHUD.jsx
  src/components/DominoHUD/HUDButtonGroup/HUDButton.jsx
  src/components/DominoHUD/HUDButtonGroup/HUDButtonGroup.jsx
  src/components/DominoHUD/SettingModal/GroundTypeButton.jsx
  src/components/DominoHUD/SettingModal/SettingGroup.jsx
  src/components/DominoHUD/SettingModal/SettingModal.jsx
  src/components/DominoHUD/index.js
  src/constants/objectPaths.js
  src/main.jsx
  src/pages/DominoScene.jsx
Labels: FE, refactor

#53 Fix: 도미노가 클릭 방향과 다른 축으로 회전하던 현상 해결
  src/hooks/useDominoSimulation.jsx
Labels: bug

#63 Feature: 대포 오브젝트 관련 애니메이션 구현
  src/constants/objectPaths.js
  src/hooks/useCannonControls.jsx
  src/pages/DominoScene.jsx
Labels: FE

#64 Fix: 배경음 클릭 재생 전환 및 도미노 효과음 볼륨 조절 기능 추가
  src/components/Common/GlobalAudio.jsx
  src/components/DominoCanvas/CursorFollowerObject/CursorFollowerObject.jsx
  src/components/DominoHUD/SettingModal/SettingModal.jsx
  src/store/useSettingStore.jsx
Labels: bug, enhancement, FE

#65 Feature: 전구, 스위치 오브젝트 구현
  public/images/lightbulb.png
  public/objects/lightbulb.glb
  src/constants/objectPaths.js
  src/pages/DominoScene.jsx
Labels: enhancement, FE

#69 Fix: 충돌 감지된 전구 외 모든 전구에 불이 켜지는 버그 수정
  src/constants/objectPaths.js
  src/pages/DominoScene.jsx
Labels: bug

#71 Feature: 핀볼 범퍼 기능 구현
  public/images/bumper.png
  public/objects/bumper.glb
  src/components/DominoCanvas/CursorFollowerObject/CursorFollowerObject.jsx
  src/constants/objectPaths.js
  src/pages/DominoScene.jsx
Labels: enhancement, FE

#76 Refactor/frontend cleanup
  jsconfig.json
  src/components/Common/ModalLayer.jsx
  src/components/DominoCanvas/CameraControls/CameraControls.jsx
  src/components/DominoCanvas/CursorFollowerObject/CursorFollowerObject.jsx
  src/components/DominoCanvas/DominoCanvas.jsx
  src/components/DominoCanvas/DominoEntity/DominoEntity.jsx
  src/components/DominoCanvas/DominoEntity/DominoVisualUnit/Bumper/Bumper.jsx
  src/components/DominoCanvas/DominoEntity/DominoVisualUnit/Cannon/Cannon.jsx
  src/components/DominoCanvas/DominoEntity/DominoVisualUnit/Car/Car.jsx
  src/components/DominoCanvas/DominoEntity/DominoVisualUnit/DominoVisualUnit.jsx
  src/components/DominoCanvas/DominoEntity/DominoVisualUnit/LightBulb/LightBulb.jsx
  src/components/DominoCanvas/ObjectRenderer/ObjectRenderer.jsx
  src/components/DominoCanvas/index.js
  src/components/DominoHUD/DominoHUD.jsx
  src/components/DominoHUD/SettingModal/SettingModal.jsx
  src/components/DominoHUD/SidePanel/DominoColorPalette.jsx
  src/components/DominoHUD/SidePanel/ObjectCard.jsx
  src/components/DominoHUD/SidePanel/SidePanel.jsx
  src/constants/objectMetaData.js
  src/pages/DominoScene.jsx
Labels: FE, refactor

#78 Chore: Vitest 테스트 환경 및 커버리지 설정 구축
  .gitignore
  package-lock.json
  package.json
  src/__test__/setupTests.js
  src/__test__/store/useDominoStore.test.jsx
  vite.config.js
Labels: config

#92 Feature: 프로젝트 생성/조회/수정/삭제(CRUD) API 연동
  src/components/DominoHUD/ProjectListModal/ProjectListModal.jsx
  src/components/DominoHUD/ProjectNameInputModal/ProjectNameInputModal.jsx
  src/hooks/useCreateProjectQueries.jsx
  src/hooks/useDeleteProjectQueries.jsx
  src/hooks/useProjectsQueries.jsx
  src/hooks/useRefreshAccessToken.jsx
  src/hooks/useUpdateProjectQueries.jsx
  src/pages/DominoScene.jsx
  src/pages/OAuthCallback.jsx
  src/routers/routes.jsx
Labels: FE

#93 Feature: 도미노 프로젝트 CRUD API 연동
  src/components/DominoCanvas/CursorFollowerObject/CursorFollowerObject.jsx
  src/components/DominoCanvas/DominoEntity/DominoEntity.jsx
  src/hooks/Queries/useDominoMutations.jsx
  src/hooks/Queries/useDominos.jsx
  src/hooks/useDominoKeyboardControls.jsx
  src/main.jsx
  src/utils/keyHandlers.js
Labels: FE

#99 Feature: 카카오 로그아웃 기능 추가 및 버튼 UI 개선
  package-lock.json
  package.json
  public/images/clear_button.png
  public/images/close_button.png
  public/images/play_button.png
  public/images/reset_button.png
  public/images/setting_button.png
  public/images/start_button.png
  public/images/stop_button.png
  public/images/undo_button.png
  src/components/Common/ModalOverlay.jsx
  src/components/DominoHUD/DominoHUD.jsx
  src/components/DominoHUD/HUDButtonGroup/HUDButton.jsx
  src/components/DominoHUD/HUDButtonGroup/HUDButtonGroup.jsx
  src/components/KakaoLogin.jsx
  src/hooks/useRefreshAccessToken.jsx
  src/pages/Home.jsx
  src/pages/LogoutCallback.jsx
  src/pages/OAuthCallback.jsx
  src/routers/routes.jsx
Labels: enhancement, FE

#105 Refactor: HUD 버튼 구조 정리 및 로그아웃 버튼 컴포넌트 분리
  src/components/DominoHUD/HUDButtonGroup/HUDButton.jsx
  src/components/DominoHUD/HUDButtonGroup/HUDButtonGroup.jsx
  src/components/DominoHUD/HUDButtonGroup/HUDLogoutButton.jsx
Labels: FE, UI

#112 Feature: GitHub Actions 기반 CI/CD 배포 워크플로 구성
  .github/workflows/deploy.yaml
Labels: config

#107 Feature: 도미노 동기화 버그 수정 및 방 제어 기능 개선
  src/components/DominoCanvas/OtherUserDominos/OtherUserDominos.jsx
  src/components/DominoHUD/DominoClearConfirmModal/DominoClearConfirmModal.jsx
  src/hooks/useDominoKeyboardControls.jsx
  src/hooks/useDominoReset.jsx
  src/main.jsx
  src/services/socket.js
  src/store/SocketContext.jsx
Labels: bug, enhancement, FE

#119 Fix: 리셋 버튼 클릭시 모든 오브젝트가 삭제되는 버그 수정
  src/constants/objectMetaData.js
  src/hooks/useDominoReset.jsx
Labels: bug

#122 Fix: 프로젝트 리스트 모달이 게임 화면에서 열리지 않는 현상
  public/objects/slide.glb
  src/components/DominoHUD/DominoHUD.jsx
  src/store/SocketContext.jsx
Labels: bug

#136 Refactor: GLB 모델에 대한 preload 로직 구현
  index.html
  public/objects/car.glb
  src/components/DominoCanvas/DominoEntity/DominoVisualUnit/Car/Car.jsx
  src/components/DominoCanvas/ObjectRenderer/ObjectRenderer.jsx
  src/constants/modelPaths.js
  src/hooks/useGlbLoader.jsx
  src/main.jsx
  src/pages/DominoScene.jsx
Labels: FE, refactor

#142 Fix: 물리 시뮬레이션 중 3D 오브젝트 엉겨붙는 현상 해결
  public/objects/car.glb
  src/components/DominoCanvas/DominoEntity/DominoEntity.jsx
  src/constants/objectMetaData.js
  src/utils/collisionGroups.js
Labels: bug

#138 Feature: 최초 사용자 대상 튜토리얼 기능 구현
  src/components/DominoCanvas/DominoCanvas.jsx
  src/components/DominoCanvas/DominoEntity/DominoEntity.jsx
  src/components/DominoCanvas/DominoEntity/DominoVisualUnit/Cannon/Cannon.jsx
  src/components/DominoCanvas/DominoEntity/TutorialStepHandler/CannonAutoPlacer/CannonAutoPlacer.jsx
  src/components/DominoCanvas/DominoEntity/TutorialStepHandler/TutorialStepHandler.jsx
  src/components/DominoCanvas/DominoEntity/TutorialStepHandler/TutorialTargetPlace/TargetPlaceholder/TargetPlaceholder.jsx
  src/components/DominoCanvas/DominoEntity/TutorialStepHandler/TutorialTargetPlace/TutorialTargetPlace.jsx
  src/components/DominoCanvas/index.js
  src/components/DominoHUD/DominoHUD.jsx
  src/components/DominoHUD/SidePanel/ObjectCard.jsx
  src/components/DominoHUD/SidePanel/SidePanel.jsx
  src/components/DominoHUD/Tutorial/Intro/Intro.jsx
  src/components/DominoHUD/Tutorial/StepCard/StepCard.jsx
  src/components/DominoHUD/Tutorial/Tutorial.jsx
  src/components/DominoHUD/index.js
  src/constants/tutorialStep.jsx
  src/hooks/Queries/useUpdateTutorialStatus.jsx
  src/hooks/useCannonControls.jsx
  src/hooks/useDominoKeyboardControls.jsx
  src/hooks/useTutorialTracker.jsx
  src/pages/OAuthCallback.jsx
  src/store/useTutorialStore.jsx
Labels: FE

#154 Refactor: UI 변경 및 사용자 경험 개선 작업
  index.html
  public/images/thumbnail/car.png
  public/images/thumbnail/spiral_stairs.png
  public/objects/car.glb
  public/objects/spiral_stairs.glb
  src/components/DominoCanvas/CameraControls/CameraControls.jsx
  src/components/DominoCanvas/CursorFollowerObject/CursorFollowerObject.jsx
  src/components/DominoCanvas/DominoEntity/DominoVisualUnit/Car/Car.jsx
  src/components/DominoHUD/DominoHUD.jsx
  src/constants/modelPaths.js
  src/constants/objectMetaData.js
  src/pages/DominoScene.jsx
  src/store/useUIStateStore.jsx
Labels: bug, FE

#156 Fix: 리셋 버튼 클릭시 도미노가 정상적으로 초기화되지 않는 현상 수정
  src/components/DominoHUD/DominoHUD.jsx
  src/hooks/useDominoReset.jsx
  src/pages/DominoScene.jsx
Labels: bug

#159 Feature: 도미노 업적 달성 초기 세팅 및 업적 내용 구축
  src/achievments/CheckDominoAchievement.jsx
  src/components/AchievementPanel.jsx
  src/components/DominoCanvas/CursorFollowerObject/CursorFollowerObject.jsx
  src/components/DominoHUD/SidePanel/DominoColorPalette.jsx
  src/hooks/useInitAchievements.jsx
  src/hooks/useStrictNavigationBlock.jsx
  src/pages/DominoScene.jsx
  src/pages/Home.jsx
  src/store/useAchievementStore.jsx
Labels: FE

#160 Feature: SEO 최적화를 위한 메타 태그 및 Search Console 등록
  index.html
  public/robots.txt
  public/sitemap.xml
Labels: config

#161 Perf: 도미노 상태 관리 및 성능 최적화 개선
  src/components/DominoCanvas/CameraControls/CameraControls.jsx
  src/components/DominoCanvas/CursorFollowerObject/CursorFollowerObject.jsx
  src/components/DominoCanvas/DominoCanvas.jsx
  src/components/DominoCanvas/DominoEntity/DominoEntity.jsx
  src/components/DominoCanvas/DominoEntity/DominoVisualUnit/DominoVisualUnit.jsx
  src/components/DominoCanvas/ObjectRenderer/ObjectRenderer.jsx
  src/components/DominoHUD/DominoHUD.jsx
  src/components/DominoHUD/HUDButtonGroup/HUDButtonGroup.jsx
  src/components/DominoHUD/HUDButtonGroup/HUDLogoutButton.jsx
  src/hooks/Queries/useDominoMutations.jsx
  src/hooks/useGlbLoader.jsx
  src/pages/DominoScene.jsx
  src/store/useUIStateStore.jsx
  src/utils/debounce.js
  src/utils/handleLogout.js
Labels: enhancement, FE

#165 Test: 외부 UI 렌더링 안정성 확보를 위한 통합 테스트 코드 작성
  src/__test__/components/DominoHUD.integration.test.jsx
  src/components/Common/ModalOverlay.jsx
  src/components/DominoHUD/HUDButtonGroup/HUDButton.jsx
  src/components/DominoHUD/HUDButtonGroup/HUDButtonGroup.jsx
Labels: test

#166 Test: 인터랙션 기반 렌더 동작 테스트 코드 작성
  src/__test__/components/SidePanel.integration.test.jsx
  src/__test__/test-utils.jsx
  src/achievments/CheckDominoAchievement.jsx
  src/components/DominoCanvas/CursorFollowerObject/CursorFollowerObject.jsx
  src/components/DominoHUD/SidePanel/DominoColorPalette.jsx
  src/components/DominoHUD/SidePanel/SidePanel.jsx
  src/hooks/useInitAchievements.jsx
  src/pages/DominoScene.jsx
  src/pages/Home.jsx
  src/store/useAchievementStore.jsx
  src/store/useUserStore.jsx
Labels: test

#168 Refactor: 도미노 상태 제거 및 서버 데이터 기반 구조로 전환
  src/components/Common/DominoKeyboardHandler.jsx
  src/components/DominoCanvas/CursorFollowerObject/CursorFollowerObject.jsx
  src/components/DominoCanvas/DominoCanvas.jsx
  src/components/DominoCanvas/DominoEntity/DominoEntity.jsx
  src/hooks/Queries/useDominoMutations.jsx
  src/hooks/Queries/useDominoOverwrite.jsx
  src/hooks/Queries/useDominos.jsx
  src/hooks/useDominoKeyboardControls.jsx
  src/hooks/useDominoReset.jsx
  src/hooks/useKeyHandler.jsx
  src/pages/DominoScene.jsx
  src/store/SocketContext.jsx
  src/utils/keyHandlers.js
Labels: refactor

#171 Ci: GitHub Actions에서 .env.production 파일 자동 생성 설정 추가
  .github/workflows/deploy.yaml
Labels: FE

#176 Fix: 서버 기반 도미노 전환 후 튜토리얼에서 도미노 감지 및 자동 배치 기능 동작하지 않는 현상 수정
  src/components/DominoCanvas/DominoEntity/TutorialStepHandler/CannonAutoPlacer/CannonAutoPlacer.jsx
  src/components/DominoCanvas/DominoEntity/TutorialStepHandler/TutorialTargetPlace/TutorialTargetPlace.jsx
Labels: bug
