Repository Domi-do/Domido, pull requests merged in 2025-05, with the labels that each got.

#9 Feature: 캔버스 초기 설정
  src/index.css
  src/pages/DominoScene.jsx
Labels: enhancement, config, FE

#11 Feature: 카메라 이동 구현
  src/hooks/useCameraControls.jsx
  src/pages/DominoScene.jsx
Labels: enhancement, FE

#13 Refactor: game page canvas UI split
  src/components/CameraControls/CameraControls.jsx
  src/components/DominoCanvas/DominoCanvas.jsx
  src/components/DominoHUD/DominoHUD.jsx
  src/pages/DominoScene.jsx
Labels: enhancement, FE

#16 Fix: git 충돌 해결
  src/components/CameraControls/CameraControls.jsx
Labels: bug

#22 Feature: 사이드 패널 - 마우스 이벤트 기능 구현
  public/images/domino.png
  public/objects/stairs_closed.glb
  src/components/CursorFollowerObject/CursorFollowerObject.jsx
  src/components/DominoCanvas/DominoCanvas.jsx
  src/components/DominoHUD/DominoHUD.jsx
  src/components/DominoHUD/SidePanel/ObjectCard.jsx
  src/components/DominoHUD/SidePanel/SidePanel.jsx
  src/components/Ground/Ground.jsx
  src/components/ObjectRenderer/ObjectRenderer.jsx
  src/constants/objectPaths.js
  src/hooks/useDominoPlacement.jsx
  src/pages/DominoScene.jsx
  src/pages/Home.jsx
  src/pages/NotFound.jsx
Labels: enhancement, FE

#24 Feature: 도미노 시뮬레이션 기능 구현
  public/images/finger_cursor.png
  public/images/play_button.png
  public/images/stop_button.png
  src/components/DominoHUD/DominoHUD.jsx
  src/components/Ground/Ground.jsx
  src/hooks/useDominoSimulation.jsx
  src/index.css
  src/pages/DominoScene.jsx
Labels: enhancement, FE, UI

#23 Feature: 오브젝트 단축키 기능 구현
  src/components/DominoHUD/DominoHUD.jsx
  src/components/DominoHUD/GuideToast/GuideToast.jsx
  src/hooks/useDominoControls.jsx
  src/pages/DominoScene.jsx
Labels: enhancement, FE

#26 Refactor: domino 기능에 대한 상태 관리 리팩토링
  package-lock.json
  package.json
  src/components/CursorFollowerObject/CursorFollowerObject.jsx
  src/components/DominoCanvas/DominoCanvas.jsx
  src/components/DominoHUD/DominoHUD.jsx
  src/components/DominoHUD/SidePanel/ObjectCard.jsx
  src/components/DominoHUD/SidePanel/SidePanel.jsx
  src/components/ObjectRenderer/ObjectRenderer.jsx
  src/hooks/useDominoControls.jsx
  src/hooks/useDominoPlacement.jsx
  src/hooks/useDominoSimulation.jsx
  src/hooks/useToastControls.jsx
  src/pages/DominoScene.jsx
  src/store/useDominoStore.jsx
  src/store/useSimulationStore.jsx
Labels: enhancement, config, FE

#33 Feature: 설정 UI 및 기능 구현
  public/images/close_button.png
  public/images/play_button.png
  public/images/reset_button.png
  public/images/setting_button.png
  src/components/DominoCanvas/DominoCanvas.jsx
  src/components/DominoHUD/DominoHUD.jsx
  src/components/Ground/Ground.jsx
  src/components/GroundTypeButton/GroundTypeButton.jsx
  src/components/ModalOverlay/ModalOverlay.jsx
  src/components/Setting/SettingGroup.jsx
  src/components/Setting/SettingModal.jsx
  src/hooks/useDominoControls.jsx
  src/hooks/useDominoSimulation.jsx
  src/hooks/useToastControls.jsx
  src/index.css
  src/pages/DominoScene.jsx
  src/store/useSettingStore.jsx
Labels: FE, UI

#37 Fix: 시뮬레이션 재실행시 물리작용 되지않는 버그 수정
  src/hooks/useDominoSimulation.jsx
  src/pages/DominoScene.jsx
Labels: bug

#40 Fix: 도미노 회전 모션 방식 수정
  src/hooks/useDominoSimulation.jsx
Labels: bug

#42 Feature: Undo & Clear 기능 구현
  public/images/undo_button.png
  src/components/DominoCanvas/DominoCanvas.jsx
  src/components/DominoHUD/DominoHUD.jsx
  src/components/UndoDisabledModal/UndoDisabledModal.jsx
  src/hooks/useDominoControls.jsx
  src/store/useDominoStore.jsx
Labels: enhancement, FE

#38 Feature: 배경음 재생 기능 구현
  public/sounds/bgm.mp3
  src/components/DominoCanvas/DominoCanvas.jsx
  src/components/GlobalAudio/GlobalAudio.jsx
  src/components/Setting/SettingModal.jsx
  src/store/useSettingStore.jsx
  src/utils/audioController.js
Labels: enhancement, FE
